## If api-gateway fails to read this file then copy all 
## these contents to the application.yml in api-gateway
server:
  port: 8078

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  tracing:
    sampling:
      probablity: 1.0

spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/emp/**
          filters:
            - name: CircuitBreaker
              args:
                name: employeeServiceCircuitBreaker
                fallbackUri: forward:/employeeServiceFallBack
            - name: AuthenticationFilter
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/dept/**
          filters:
            - name: CircuitBreaker
              args:
                name: departmentServiceCircuitBreaker
                fallbackUri: forward:/departmentServiceFallBack
            - name: AuthenticationFilter
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 1s
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
  instances:
    employeeServiceCircuitBreaker:
      baseConfig: default
    #      registerHealthIndicator: true
    #      waitDurationInOpenState: 1s
    departmentServiceCircuitBreaker:
      baseConfig: default
#      registerHealthIndicator: true
#      waitDurationInOpenState: 1s
